---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: portal-mysql-slave-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50G
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-master-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50G
